/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usbbog.is.proyecto.integradorr.vista;

import co.edu.is.proyecto.integrador.logicas.GestionRegistrosTestimonios;
import co.edu.is.proyecto.integrador.logicas.GestionTestimonio;
import co.edu.is.proyecto.integrador.logicas.GestionUsuario;

/**
 *
 * @author orion
 */
public class Principal extends javax.swing.JFrame {
    GestionTestimonio gestionTestimonio;
    Jpanelvictima victima;
    PaneUsuario usuarioPanel;
    Panel_conf_usuario configUsuario;
    GestionRegistrosTestimonios gestionregistros;
    GestionUsuario gestionusuario;
    /**
     * Creates new form Principal
     */
    public Principal() {
gestionTestimonio = new GestionTestimonio();
victima = new Jpanelvictima(this);
configUsuario = new Panel_conf_usuario(this);
        
        
      setTitle("peluqueria.com");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        victima.setVisible(true);
        
        add(victima);
       
        pack();
        setLocationRelativeTo(null);   
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
           new Principal().setVisible(true);
        });
    }

    public void irDetalle( Jpanelvictima victima){
        this.remove(victima);
        gestionTestimonio = new GestionTestimonio();
        configUsuario = new Panel_conf_usuario(this);
        configUsuario.setVisible(true);
        this.add(configUsuario);
        pack();
        setLocationRelativeTo(null);}
    
    public void irConfUsuario(Jpanelvictima victima){
     this.remove(victima);
        gestionTestimonio = new GestionTestimonio();
        usuarioPanel = new PaneUsuario(this);
        usuarioPanel.setVisible(true);
        this.add(usuarioPanel);
        pack();
        setLocationRelativeTo(null);
         
    }
    public void irDetalleDesdeConf( PaneUsuario usuarioPanel){
        this.remove( usuarioPanel);
        gestionTestimonio = new GestionTestimonio();
        this.victima= new     Jpanelvictima(this);
        this.victima.setVisible(true);
        this.add(victima);
        pack();
        setLocationRelativeTo(null);
    }
 
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
